# Site settings
remote_theme: JeremySkinner/PrettyDocs-theme
url: https://fluentvalidation.net/
title: &site_title FluentValidation
branding:
  highlight: Fluent
  bold: Validation

# Owner
owner:
  name: Jeremy Skinner
  twitter: &site_owner_twitter JeremySkinner
  copyright:
    author: "[Jeremy Skinner](http://jeremyskinner.co.uk/)"

# Google Analytics
google_analytics: UA-884625-14